<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[HomePage_test==== Execution Started ]]>
    </line>
    <line>
      <![CDATA[HomePage_test==== Execution onTestFailure Failed ]]>
    </line>
    <line>
      <![CDATA[HomePage_test==== Execution Started ]]>
    </line>
    <line>
      <![CDATA[HomePage_test==== Execution onTestFailure Failed ]]>
    </line>
    <line>
      <![CDATA[HomePage_test==== Execution Started ]]>
    </line>
    <line>
      <![CDATA[HomePage_test==== Execution onTestFailure Failed ]]>
    </line>
  </reporter-output>
  <suite started-at="2024-07-11T01:29:56 IST" name="Default suite" finished-at="2024-07-11T01:31:39 IST" duration-ms="102757">
    <groups>
    </groups>
    <test started-at="2024-07-11T01:29:56 IST" name="Default test" finished-at="2024-07-11T01:31:39 IST" duration-ms="102757">
      <class name="com.BusinessLogic.TestCase1">
        <test-method is-config="true" signature="Config_bc(java.lang.String)[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:29:56 IST" name="Config_bc" finished-at="2024-07-11T01:30:02 IST" duration-ms="5696" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Config_bc -->
        <test-method is-config="true" signature="loginSetup()[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:30:02 IST" name="loginSetup" finished-at="2024-07-11T01:30:04 IST" duration-ms="1392" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSetup -->
        <test-method retried="true" signature="HomePage_test()[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:30:04 IST" name="HomePage_test" finished-at="2024-07-11T01:30:10 IST" duration-ms="6076" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.BusinessLogic.TestCase1.HomePage_test(TestCase1.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HomePage_test==== Execution Started ]]>
            </line>
            <line>
              <![CDATA[HomePage_test==== Execution onTestFailure Failed ]]>
            </line>
          </reporter-output>
        </test-method> <!-- HomePage_test -->
        <test-method is-config="true" signature="appShutdown()[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:30:10 IST" name="appShutdown" finished-at="2024-07-11T01:30:11 IST" duration-ms="1156" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appShutdown -->
        <test-method is-config="true" signature="loginSetup()[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:30:11 IST" name="loginSetup" finished-at="2024-07-11T01:30:13 IST" duration-ms="2203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSetup -->
        <test-method retried="true" signature="HomePage_test()[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:30:13 IST" name="HomePage_test" finished-at="2024-07-11T01:30:55 IST" duration-ms="41531" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.BusinessLogic.TestCase1.HomePage_test(TestCase1.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HomePage_test==== Execution Started ]]>
            </line>
            <line>
              <![CDATA[HomePage_test==== Execution onTestFailure Failed ]]>
            </line>
          </reporter-output>
        </test-method> <!-- HomePage_test -->
        <test-method is-config="true" signature="appShutdown()[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:30:55 IST" name="appShutdown" finished-at="2024-07-11T01:30:55 IST" duration-ms="868" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appShutdown -->
        <test-method is-config="true" signature="loginSetup()[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:30:55 IST" name="loginSetup" finished-at="2024-07-11T01:30:56 IST" duration-ms="775" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSetup -->
        <test-method signature="HomePage_test()[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:30:56 IST" name="HomePage_test" finished-at="2024-07-11T01:31:38 IST" duration-ms="41456" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.BusinessLogic.TestCase1.HomePage_test(TestCase1.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[HomePage_test==== Execution Started ]]>
            </line>
            <line>
              <![CDATA[HomePage_test==== Execution onTestFailure Failed ]]>
            </line>
          </reporter-output>
        </test-method> <!-- HomePage_test -->
        <test-method is-config="true" signature="appShutdown()[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:31:38 IST" name="appShutdown" finished-at="2024-07-11T01:31:39 IST" duration-ms="778" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appShutdown -->
        <test-method is-config="true" signature="Teardown()[pri:0, instance:com.BusinessLogic.TestCase1@2e3967ea]" started-at="2024-07-11T01:31:39 IST" name="Teardown" finished-at="2024-07-11T01:31:39 IST" duration-ms="231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- com.BusinessLogic.TestCase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
